<style>
    .mi_fila{
        margin-top: 50px;
        margin-bottom: 100px;
    }

    .mi_titulo{
        margin-bottom:40px;
    }   

    .mi_tabla td{
        cursor:pointer;
    }

</style>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>

<div class="row mi_fila">
    <div class="col-md-12">
        <h3 class="mi_titulo">Zend Framework CRUD TableGateway ORM</h3>
        <form id="fornm1" name="form1" action="<?php echo $this->basePath().'/application/add' ?>" method="post">
        <table class="mi_tabla td table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                </tr>
            </thead>
            <tbody>
               <tr>
                   <td>#</td>
                   <td><input type="text" name="title" id="title" value="" style="width:90%;"></td>
                   <td><input type="text" name="description" id="description" value="" style="width:90%;"></td>
                </tr>        
            </tbody>
        </table>
        <!-- hidden -->
        <input type="hidden" name="created_at" id="created_at" value="<?php echo date('Y-m-d H:i:s'); ?>">
        <input type="hidden" name="id" id="id" value="">
        <!-- submit -->
        <input name="guardar" id="guardar" type="submit" value="Save" class="btn-success btn btn-lg">
        </form>
    </div>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Follow Development</h2>
            </div>
            <div class="card-body">
                <p>
                    Zend Framework is under active development. If you are
                    interested in following the development of ZF, you can check
                    <a href="http://framework.zend.com/blog/">ZF dev blog</a>,
                    and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:zendframework">ZF issue tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>

                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">ZF Development Portal &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Discover Modules</h2>
            </div>
            <div class="card-body">
                <p>
                    The community is working on developing a community site to
                    serve as a repository and gallery for ZF modules. The
                    project is available <a href="https://github.com/zendframework/modules.zendframework.com">on GitHub</a>.
                    The site is currently live and currently contains a list of
                    some of the modules already available for ZF.
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Help &amp; Support</h2>
            </div>
            <div class="card-body">
                <p>
                    If you need any help or support while developing with ZF,
                    you may reach us via IRC: <a href="irc://irc.freenode.net/zftalk">#zftalk on Freenode</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding this release. Alternatively, you may subscribe
                    and post questions to the <a href="http://framework.zend.com/archives/">mailing lists</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
